Fix - TypeError: 'ABCMeta' object is not subscriptable - AttributeError: partially initialized module 'firebase_admin._user_mgt' has no attribute 'UserMetadata' (most likely due to a circular import) - db.Reference signature